### ISSUE TITLE
Unable to download the SBT plugin 

### ISSUE THREAD

**Issue by viswanath7** [kiemlicz/shelm#10]
Hello, 

I am trying to use your SBT plugin for Helm but I'm struggling to download it. I encounter the following error 

`[error] (update) sbt.librarymanagement.ResolveException: Error downloading com.kiemlicz:shelm;sbtVersion=1.0;scalaVersion=2.12:0.5.3
[error]   Not found
[error]   Not found
[error]   not found: https://repo1.maven.org/maven2/com/kiemlicz/shelm_2.12_1.0/0.5.3/shelm-0.5.3.pom
[error]   not found: /Users/viswanath/.ivy2/local/com.kiemlicz/shelm/scala_2.12/sbt_1.0/0.5.3/ivys/ivy.xml
[error]   not found: https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.kiemlicz/shelm/scala_2.12/sbt_1.0/0.5.3/ivys/ivy.xml
[error]   not found: https://repo.typesafe.com/typesafe/ivy-releases/com.kiemlicz/shelm/scala_2.12/sbt_1.0/0.5.3/ivys/ivy.xml`

Is there a plugin repository that I need to add to SBT plugin resolvers? If so, can you please guide me to accomplish that?

Thanks in advance!

**Comment by kiemlicz** [comment]
Hello,

Thank you for this information, and sorry for the inconvenience.  
I forgot to update the README with proper plugin config.

Now the README is fine, please set in `project/plugins.sbt`:
```
addSbtPlugin("io.github.kiemlicz" % "shelm" % "0.5.3")
```
The `com.kiemlicz` has been used when the bintray was active, since its shutdown I've moved the project to maven central thus no extra resolvers need to be configured.

Please let me know if that solves your issue

**Comment by kiemlicz** [comment]
Please re-open if the issue persist
